
--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

--Q11. Segment customers into High-Value, Medium, and Low-Value based on spend and frequency
WITH scored AS (
    SELECT *,
           NTILE(3) OVER (ORDER BY purchase_amount DESC) AS value_score,
           CASE 
               WHEN frequency_of_purchases IN ('Weekly', 'Bi-Weekly') THEN 3
               WHEN frequency_of_purchases IN ('Fortnightly', 'Monthly') THEN 2
               ELSE 1
           END AS frequency_score
    FROM public.customer
),
segmented AS (
    SELECT *,
           CASE 
               WHEN value_score = 1 AND frequency_score >= 2 THEN 'High-Value'
               WHEN value_score <= 2 AND frequency_score >= 2 THEN 'Medium'
               ELSE 'Low-Value'
           END AS customer_segment
    FROM scored
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM segmented
GROUP BY customer_segment
ORDER BY avg_spend DESC;

--Q12. Which payment methods have the highest average purchase amount? (Top 5)
SELECT 
    payment_method,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase_amount,
    COUNT(*) AS transaction_count
FROM public.customer
GROUP BY payment_method
ORDER BY avg_purchase_amount DESC
LIMIT 5;

--Q13. Which categories sell the most in each season?
SELECT 
    season,
    category,
    COUNT(*) AS total_sales,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM public.customer
GROUP BY season, category
ORDER BY season, total_sales DESC;

--Q14. Do subscribed customers shop more frequently than non-subscribers?
SELECT 
    subscription_status,
    frequency_of_purchases,
    COUNT(*) AS customer_count
FROM public.customer
GROUP BY subscription_status, frequency_of_purchases
ORDER BY subscription_status,
         CASE frequency_of_purchases
             WHEN 'Weekly' THEN 1
             WHEN 'Bi-Weekly' THEN 2
             WHEN 'Fortnightly' THEN 3
             WHEN 'Monthly' THEN 4
             WHEN 'Every 3 Months' THEN 5
             WHEN 'Quarterly' THEN 6
             WHEN 'Annually' THEN 7
         END;

--Q15. What is the average age of customers who used a discount vs. those who didn't?
SELECT 
    discount_applied,
    ROUND(AVG(age)::numeric, 1) AS avg_age,
    COUNT(*) AS customer_count
FROM public.customer
GROUP BY discount_applied;


--Q16. In which states is Express shipping most preferred? (Percentage, top 10)
SELECT 
    location,
    ROUND(100.0 * SUM(CASE WHEN shipping_type = 'Express' THEN 1 ELSE 0 END) / COUNT(*), 2) AS express_shipping_rate
FROM public.customer
GROUP BY location
HAVING COUNT(*) >= 5
ORDER BY express_shipping_rate DESC
LIMIT 10;

--Q17. What is the average number of previous purchases for customers who used a discount?
SELECT 
    discount_applied,
    ROUND(AVG(previous_purchases)::numeric, 1) AS avg_previous_purchases,
    COUNT(*) AS total_customers
FROM public.customer
GROUP BY discount_applied;

--Q18. Which colors are most preferred by customers who gave high ratings (≥4.5)?
SELECT 
    color,
    COUNT(*) AS high_rated_purchases
FROM public.customer
WHERE review_rating::numeric >= 4.5
GROUP BY color
ORDER BY high_rated_purchases DESC
LIMIT 5;

----Q19. Do customers with Free Shipping spend more than those with paid shipping?
SELECT 
    CASE WHEN shipping_type = 'Free Shipping' THEN 'Free Shipping' ELSE 'Paid Shipping' END AS shipping_category,
    ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend,
    COUNT(*) AS transaction_count
FROM public.customer
GROUP BY CASE WHEN shipping_type = 'Free Shipping' THEN 'Free Shipping' ELSE 'Paid Shipping' END;